package com.gamebox_idtkown.core.db.greendao;

import com.liulishuo.filedownloader.BaseDownloadTask;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "DOWNLOAD_INFO".
 */
@Entity
public class DownloadInfo {

    @Id(autoincrement = true)
    public Long id;
    public String name;
    public String url;
    public String packageName;
    public String iconUrl;
    public String desc;
    public String speed;
    public String size;
    public Float precent;
    public Integer status;
    public Boolean isUpdate;
    public String gameId;
    public String type;

    public boolean canDownloadIn234G = false;

    @Transient
    public BaseDownloadTask downloadTask;

    @Transient
    public boolean menuExpand = false;

    @Transient
    public boolean isDelete = false;

    @Transient
    public boolean isInstall = true;

    @Generated
    public DownloadInfo() {
    }

    public DownloadInfo(Long id) {
        this.id = id;
    }

    @Generated
    public DownloadInfo(Long id, String name, String url, String packageName, String iconUrl, String desc, String speed, String size, Float precent, Integer status, Boolean isUpdate, String gameId, String type) {
        this.id = id;
        this.name = name;
        this.url = url;
        this.packageName = packageName;
        this.iconUrl = iconUrl;
        this.desc = desc;
        this.speed = speed;
        this.size = size;
        this.precent = precent;
        this.status = status;
        this.isUpdate = isUpdate;
        this.gameId = gameId;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getPackageName() {
        if(packageName == null){
            packageName = "";
        }
        return packageName;
    }

    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    public String getIconUrl() {
        return iconUrl;
    }

    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public String getSpeed() {
        return speed;
    }

    public void setSpeed(String speed) {
        this.speed = speed;
    }

    public String getSize() {
        return size;
    }

    public void setSize(String size) {
        this.size = size;
    }

    public Float getPrecent() {
        if(precent == null){
            precent = 0.0f;
        }
        return precent;
    }

    public void setPrecent(Float precent) {
        this.precent = precent;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Boolean getIsUpdate() {
        if(isUpdate == null){
            isUpdate = false;
        }
        return isUpdate;
    }

    public void setIsUpdate(Boolean isUpdate) {
        this.isUpdate = isUpdate;
    }

    public String getGameId() {
        return gameId;
    }

    public void setGameId(String gameId) {
        this.gameId = gameId;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

}
