package com.gamebox_idtkown.core.db.greendao;

import com.alibaba.fastjson.annotation.JSONField;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "EARN_POINT_TASK_INFO".
 */
@Entity
public class EarnPointTaskInfo {

    @Id(autoincrement = true)
    @JSONField(serialize = false)
    private Long id;

    private String log_action_name;
    private String log_point;
    private String point_action_id;
    private String point;
    private String name;
    private String bind_mobile;
    private String title;
    private String title_sub;
    private String desp;
    private String ico;
    private String type;
    private String app_active;
    private String share_content;

    @Generated
    public EarnPointTaskInfo() {
    }

    public EarnPointTaskInfo(Long id) {
        this.id = id;
    }

    @Generated
    public EarnPointTaskInfo(Long id, String log_action_name, String log_point, String point_action_id, String point, String name, String bind_mobile, String title, String title_sub, String desp, String ico, String type, String app_active, String share_content) {
        this.id = id;
        this.log_action_name = log_action_name;
        this.log_point = log_point;
        this.point_action_id = point_action_id;
        this.point = point;
        this.name = name;
        this.bind_mobile = bind_mobile;
        this.title = title;
        this.title_sub = title_sub;
        this.desp = desp;
        this.ico = ico;
        this.type = type;
        this.app_active = app_active;
        this.share_content = share_content;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLog_action_name() {
        if (log_action_name == null) {
            log_action_name = "";
        }
        return log_action_name;
    }

    public void setLog_action_name(String log_action_name) {
        if (log_action_name == null) {
            log_action_name = "";
        }
        this.log_action_name = log_action_name;
    }

    public String getLog_point() {
        if (log_point == null) {
            log_point = "";
        }
        return log_point;
    }

    public void setLog_point(String log_point) {
        if (log_point == null) {
            log_point = "";
        }
        this.log_point = log_point;
    }

    public String getPoint_action_id() {
        return point_action_id;
    }

    public void setPoint_action_id(String point_action_id) {
        this.point_action_id = point_action_id;
    }

    public String getPoint() {
        return point;
    }

    public void setPoint(String point) {
        this.point = point;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getBind_mobile() {
        return bind_mobile;
    }

    public void setBind_mobile(String bind_mobile) {
        this.bind_mobile = bind_mobile;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getTitle_sub() {
        return title_sub;
    }

    public void setTitle_sub(String title_sub) {
        this.title_sub = title_sub;
    }

    public String getDesp() {
        return desp;
    }

    public void setDesp(String desp) {
        this.desp = desp;
    }

    public String getIco() {
        return ico;
    }

    public void setIco(String ico) {
        this.ico = ico;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getApp_active() {
        return app_active;
    }

    public void setApp_active(String app_active) {
        this.app_active = app_active;
    }

    public String getShare_content() {
        if (share_content == null) {
            share_content = "";
        }
        return share_content;
    }

    public void setShare_content(String share_content) {
        if (share_content == null) {
            share_content = "";
        }
        this.share_content = share_content;
    }

}
