package com.gamebox_idtkown.core.db.greendao;

import org.greenrobot.greendao.annotation.*;

import java.util.List;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "GAME_DETAIL".
 */
@Entity
public class GameDetail {

    @Id
    private Long id;
    private String gameId;
    private String body;
    private String shareUrl;
    private Boolean hasGift;
    @Transient
    public List<GameImage> imgs;

    @Generated
    public GameDetail() {
    }

    public GameDetail(Long id) {
        this.id = id;
    }

    @Generated
    public GameDetail(Long id, String gameId, String body, String shareUrl, Boolean hasGift) {
        this.id = id;
        this.gameId = gameId;
        this.body = body;
        this.shareUrl = shareUrl;
        this.hasGift = hasGift;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getGameId() {
        return gameId;
    }

    public void setGameId(String gameId) {
        this.gameId = gameId;
    }

    public String getBody() {
        return body;
    }

    public void setBody(String body) {
        this.body = body;
    }

    public String getShareUrl() {
        return shareUrl;
    }

    public void setShareUrl(String shareUrl) {
        this.shareUrl = shareUrl;
    }

    public Boolean getHasGift() {
        return hasGift;
    }

    public void setHasGift(Boolean hasGift) {
        this.hasGift = hasGift;
    }

}
