package com.gamebox_idtkown.core.db.greendao;

import com.alibaba.fastjson.annotation.JSONField;
import com.gamebox_idtkown.core.ApkStatus;

import org.greenrobot.greendao.annotation.*;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "GAME_INFO".
 */
@Entity
public class GameInfo implements Serializable {

    public static final long serialVersionUID = 0x1122221;

    @Id
    private Long id;
    @JSONField(name = "game_id")
    private String gameId;

    private String name;

    private String type;

    @JSONField(name = "package_name")
    private String packageName;

    private String down_url;
    private String url;

    @JSONField(name = "ico")
    private String iconUrl;

    @JSONField(name = "cate_name")
    private String cateName;

    @JSONField(name = "desp")
    private String desc;

    @JSONField(name = "version_name")
    private String version;

    @JSONField(name = "size")
    private int totalSize;

    @JSONField(name = "download_times")
    private String downloadTimes;

    @JSONField(name = "update_time")
    private String updateTime;
    private String cacheType;
    private String money;

    @JSONField(name = "has_gift")
    private Integer hasGift;

    public Integer status;

    public boolean isUpdate = false;

    private String size_text;

    public ChosenInfo chosenInfo;

    public boolean isdownload = false;



    @Generated
    public GameInfo() {
    }

    public GameInfo(Long id) {
        this.id = id;
    }

    @Generated
    public GameInfo(Long id, String gameId, String name, String type, String packageName, String url, String
            down_url, String iconUrl, String cateName, String desc, String version, Integer totalSize, String
                            downloadTimes, String updateTime, String cacheType, String money, Integer hasGift, String size_text) {
        this.id = id;
        this.gameId = gameId;
        this.name = name;
        this.type = type;
        this.packageName = packageName;
        this.url = url;
        this.down_url = down_url;
        this.iconUrl = iconUrl;
        this.cateName = cateName;
        this.desc = desc;
        this.version = version;
        this.totalSize = totalSize;
        this.downloadTimes = downloadTimes;
        this.updateTime = updateTime;
        this.cacheType = cacheType;
        this.money = money;
        this.hasGift = hasGift;
        this.size_text = size_text;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getGameId() {
        return gameId;
    }

    public void setGameId(String gameId) {
        this.gameId = gameId;
    }

    public String getName() {
        if (name == null) {
            name = "";
        }
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getPackageName() {
        if (packageName == null) {
            packageName = "";
        }
        return packageName;
    }

    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    public String getUrl() {
        if (down_url == null || down_url.isEmpty()) {
            if (url == null) {
                url = "";
            }
            return url;
        }
        return down_url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getDown_url() {
        return down_url;
    }

    public void setDown_url(String down_url) {
        this.down_url = down_url;
    }

    public String getIconUrl() {
        return iconUrl;
    }

    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl;
    }

    public String getCateName() {
        if(cateName == null){
            cateName = "";
        }
        return cateName;
    }

    public void setCateName(String cateName) {
        this.cateName = cateName;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public Integer getTotalSize() {
        return totalSize;
    }

    public void setTotalSize(Integer totalSize) {
        this.totalSize = totalSize;
    }

    public String getDownloadTimes() {
        return downloadTimes;
    }

    public void setDownloadTimes(String downloadTimes) {
        this.downloadTimes = downloadTimes;
    }

    public String getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    public String getCacheType() {
        return cacheType;
    }

    public void setCacheType(String cacheType) {
        this.cacheType = cacheType;
    }

    public String getMoney() {
        return money;
    }

    public void setMoney(String money) {
        this.money = money;
    }

    public Integer getHasGift() {
        if (hasGift == null) {
            hasGift = 0;
        }
        return hasGift;
    }

    public void setHasGift(Integer hasGift) {
        this.hasGift = hasGift;
    }

    public String getSize_text() {
        return size_text;
    }

    public void setSize_text(String size_text) {
        this.size_text = size_text;
    }

    public Integer getStatus() {
        if (status == null) {
            status = ApkStatus.UNDOWNLOAD;
        }
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

}
