package com.gamebox_idtkown.core.db.greendao;

import com.alibaba.fastjson.annotation.JSONField;

import org.greenrobot.greendao.annotation.*;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "GAME_TYPE".
 */
@Entity
public class GameType implements Serializable {
    public static final long serialVersionUID = 0x121001;

    @Id
    private Long id;
    @JSONField(name = "id")
    private String tid;
    private String name;
    @JSONField(name = "ico")
    private String iconUrl;
    private String size;
    private String desp;

    @Generated
    public GameType() {
    }

    public GameType(Long id) {
        this.id = id;
    }

    @Generated
    public GameType(Long id, String tid, String name, String iconUrl, String size, String desp) {
        this.id = id;
        this.tid = tid;
        this.name = name;
        this.iconUrl = iconUrl;
        this.size = size;
        this.desp = desp;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTid() {
        return tid;
    }

    public void setTid(String tid) {
        this.tid = tid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getIconUrl() {
        return iconUrl;
    }

    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl;
    }

    public String getSize() {
        return size;
    }

    public void setSize(String size) {
        this.size = size;
    }

    public String getDesp() {
        return desp;
    }

    public void setDesp(String desp) {
        this.desp = desp;
    }

}
