package com.gamebox_idtkown.core.db.greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "GAME_IMAGE".
 */
@Entity
public class GameImage {

    @Id
    private Long id;
    private String gameId;
    private String imgUrl;

    @Generated
    public GameImage() {
    }

    public GameImage(Long id) {
        this.id = id;
    }

    @Generated
    public GameImage(Long id, String gameId, String imgUrl) {
        this.id = id;
        this.gameId = gameId;
        this.imgUrl = imgUrl;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getGameId() {
        return gameId;
    }

    public void setGameId(String gameId) {
        this.gameId = gameId;
    }

    public String getImgUrl() {
        return imgUrl;
    }

    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

}
