package com.gamebox_idtkown.core.db.greendao;

import com.alibaba.fastjson.annotation.JSONField;

import org.greenrobot.greendao.annotation.*;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "GIFT_DETAIL".
 */
@Entity
public class GiftDetail implements Serializable {
    public static final long serialVersionUID = 0x1121131;

    @Id(autoincrement = true)
    private Long id;
    private String gameId;
    private String type;
    private String name;
    private String content;
    @JSONField(name = "img")
    private String imgUrl;

    @JSONField(name = "total_num")
    private String totalNum;

    @JSONField(name = "remain_num")
    private String surplusNum;

    @JSONField(name = "price")
    private String point;

    private Boolean isPay;
    private String access_date;


    @JSONField(name = "id")
    private String giftId;
    private String code;
    private String goods_id;
    private String goods_type_id;
    private String change_note;
    private String desp;

    @JSONField(name = "is_pay")
    public String fixisPay = "0";

    @Generated
    public GiftDetail() {
    }

    public GiftDetail(Long id) {
        this.id = id;
    }

    @Generated
    public GiftDetail(Long id, String gameId, String type, String name, String content, String imgUrl, String totalNum, String surplusNum, String point, Boolean isPay, String access_date, String giftId, String code, String goods_id, String goods_type_id, String change_note, String desp) {
        this.id = id;
        this.gameId = gameId;
        this.type = type;
        this.name = name;
        this.content = content;
        this.imgUrl = imgUrl;
        this.totalNum = totalNum;
        this.surplusNum = surplusNum;
        this.point = point;
        this.isPay = isPay;
        this.access_date = access_date;
        this.giftId = giftId;
        this.code = code;
        this.goods_id = goods_id;
        this.goods_type_id = goods_type_id;
        this.change_note = change_note;
        this.desp = desp;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getGameId() {
        return gameId;
    }

    public void setGameId(String gameId) {
        this.gameId = gameId;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getImgUrl() {
        return imgUrl;
    }

    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    public String getTotalNum() {
        return totalNum;
    }

    public void setTotalNum(String totalNum) {
        this.totalNum = totalNum;
    }

    public String getSurplusNum() {
        return surplusNum;
    }

    public void setSurplusNum(String surplusNum) {
        this.surplusNum = surplusNum;
    }

    public String getPoint() {
        return point;
    }

    public void setPoint(String point) {
        this.point = point;
    }

    public Boolean getIsPay() {
        return isPay;
    }

    public void setIsPay(Boolean isPay) {
        this.isPay = isPay;
    }

    public String getAccess_date() {
        return access_date;
    }

    public void setAccess_date(String access_date) {
        this.access_date = access_date;
    }

    public String getGiftId() {
        return giftId;
    }

    public void setGiftId(String giftId) {
        this.giftId = giftId;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getGoods_id() {
        return goods_id;
    }

    public void setGoods_id(String goods_id) {
        this.goods_id = goods_id;
    }

    public String getGoods_type_id() {
        return goods_type_id;
    }

    public void setGoods_type_id(String goods_type_id) {
        this.goods_type_id = goods_type_id;
    }

    public String getChange_note() {
        return change_note;
    }

    public void setChange_note(String change_note) {
        this.change_note = change_note;
    }

    public String getDesp() {
        return desp;
    }

    public void setDesp(String desp) {
        this.desp = desp;
    }

}
