package com.gamebox_idtkown.core.db.greendao;

import com.alibaba.fastjson.annotation.JSONField;

import org.greenrobot.greendao.annotation.*;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "GIFT_INDEX".
 */
@Entity
public class GiftIndex implements Serializable{
    public static final long serialVersionUID = 0x6123;

    @Id
    private Long id;
    @JSONField(name = "game_id")
    private String gameId;

    @JSONField(name = "game_name")
    private String gameName;

    @JSONField(name = "last_gift_name")
    private String lastGiftName;

    @JSONField(name = "ico")
    private String iconUrl;

    private String num;

    @Generated
    public GiftIndex() {
    }

    public GiftIndex(Long id) {
        this.id = id;
    }

    @Generated
    public GiftIndex(Long id, String gameId, String gameName, String lastGiftName, String iconUrl, String num) {
        this.id = id;
        this.gameId = gameId;
        this.gameName = gameName;
        this.lastGiftName = lastGiftName;
        this.iconUrl = iconUrl;
        this.num = num;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getGameId() {
        return gameId;
    }

    public void setGameId(String gameId) {
        this.gameId = gameId;
    }

    public String getGameName() {
        return gameName;
    }

    public void setGameName(String gameName) {
        this.gameName = gameName;
    }

    public String getLastGiftName() {
        return lastGiftName;
    }

    public void setLastGiftName(String lastGiftName) {
        this.lastGiftName = lastGiftName;
    }

    public String getIconUrl() {
        return iconUrl;
    }

    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl;
    }

    public String getNum() {
        return num;
    }

    public void setNum(String num) {
        this.num = num;
    }

}
