package com.gamebox_idtkown.core.db.greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "GOOD_CHANGE".
 */
@Entity
public class GoodChange {

    @Id
    private Long id;
    private String goods_name;
    private String goods_img;
    private String goodId;
    private String goods_price;
    private String user_id;
    private String trade_time_text;
    private String gift_code;

    public String getGoods_desp() {
        return goods_desp;
    }

    public void setGoods_desp(String goods_desp) {
        this.goods_desp = goods_desp;
    }

    private String goods_desp;

    public String getGoods_type_id() {
        return goods_type_id;
    }

    public void setGoods_type_id(String goods_type_id) {
        this.goods_type_id = goods_type_id;
    }

    private String goods_type_id;

    public String getGoods_type_val() {
        return goods_type_val;
    }

    public void setGoods_type_val(String goods_type_val) {
        this.goods_type_val = goods_type_val;
    }

    private String goods_type_val;

    @Generated
    public GoodChange() {
    }

    public GoodChange(Long id) {
        this.id = id;
    }

    @Generated
    public GoodChange(Long id, String goods_name, String goods_img, String goodId, String goods_price, String user_id, String trade_time_text) {
        this.id = id;
        this.goods_name = goods_name;
        this.goods_img = goods_img;
        this.goodId = goodId;
        this.goods_price = goods_price;
        this.user_id = user_id;
        this.trade_time_text = trade_time_text;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getGoods_name() {
        return goods_name;
    }

    public void setGoods_name(String goods_name) {
        this.goods_name = goods_name;
    }

    public String getGoods_img() {
        return goods_img;
    }

    public void setGoods_img(String goods_img) {
        this.goods_img = goods_img;
    }

    public String getGoodId() {
        return goodId;
    }

    public void setGoodId(String goodId) {
        this.goodId = goodId;
    }

    public String getGoods_price() {
        return goods_price;
    }

    public void setGoods_price(String goods_price) {
        this.goods_price = goods_price;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getTrade_time_text() {
        return trade_time_text;
    }

    public void setTrade_time_text(String trade_time_text) {
        this.trade_time_text = trade_time_text;
    }


    public String getGift_code() {
        return gift_code;
    }

    public void setGift_code(String gift_code) {
        this.gift_code = gift_code;
    }
}
