package com.gamebox_idtkown.core.db.greendao;

import com.alibaba.fastjson.annotation.JSONField;

import org.greenrobot.greendao.annotation.*;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "GOOD_TYPE".
 */
@Entity
public class GoodType implements Serializable {
    public static final long serialVersionUID = 0x11a21;

    @Id
    private Long id;
    @JSONField(name = "id")
    private String typeId;
    private String name;
    private String title;
    private String ico;
    private String total_num;
    private String total_convert;
    private String game_id;

    public String getGame_id() {
        return game_id;
    }

    public void setGame_id(String game_id) {
        this.game_id = game_id;
    }


    @Generated
    public GoodType() {
    }

    public GoodType(Long id) {
        this.id = id;
    }

    @Generated
    public GoodType(Long id, String typeId, String name, String title, String ico, String total_num, String total_convert) {
        this.id = id;
        this.typeId = typeId;
        this.name = name;
        this.title = title;
        this.ico = ico;
        this.total_num = total_num;
        this.total_convert = total_convert;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTypeId() {
        return typeId;
    }

    public void setTypeId(String typeId) {
        this.typeId = typeId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getIco() {
        return ico;
    }

    public void setIco(String ico) {
        this.ico = ico;
    }

    public String getTotal_num() {
        if(total_num == null){
            total_num = "0";
        }
        return total_num;
    }

    public void setTotal_num(String total_num) {
        this.total_num = total_num;
    }

    public String getTotal_convert() {
        if(total_convert == null){
            total_convert = "0";
        }
        return total_convert;
    }

    public void setTotal_convert(String total_convert) {
        this.total_convert = total_convert;
    }

}
