package com.gamebox_idtkown.core.db.greendao;

import com.alibaba.fastjson.annotation.JSONField;

import org.greenrobot.greendao.annotation.*;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "GOOD_LIST".
 */
@Entity
public class GoodList implements Serializable {

    @Id
    private Long id;
    private String curr_stock;
    private String desp;
    private String game_id;
    private String game_name;
    @JSONField(name = "id")
    private String goodId;
    private String img;
    private String is_comm;
    private String max_buy_num;
    private String name;
    private String price;
    private String status;
    private String stock;
    private String type_id;
    private String type_name;
    private String type_val;
    private String uc_start_time;
    private String uc_end_time;

    private String uc_money;

    public String getUc_money() {
        return uc_money;
    }

    public void setUc_money(String uc_money) {
        this.uc_money = uc_money;
    }

    public String getUc_start_time() {
        return uc_start_time;
    }

    public void setUc_start_time(String uc_start_time) {
        this.uc_start_time = uc_start_time;
    }

    public String getUc_end_time() {
        return uc_end_time;
    }

    public void setUc_end_time(String uc_end_time) {
        this.uc_end_time = uc_end_time;
    }

    public String getUse_method() {
        return use_method;
    }

    public void setUse_method(String use_method) {
        this.use_method = use_method;
    }

    private String use_method;

    @Generated
    public GoodList() {
    }

    public GoodList(Long id) {
        this.id = id;
    }

    @Generated
    public GoodList(Long id, String curr_stock, String desp, String game_id, String game_name, String goodId, String img, String is_comm, String max_buy_num, String name, String price, String status, String stock, String type_id, String type_name, String type_val) {
        this.id = id;
        this.curr_stock = curr_stock;
        this.desp = desp;
        this.game_id = game_id;
        this.game_name = game_name;
        this.goodId = goodId;
        this.img = img;
        this.is_comm = is_comm;
        this.max_buy_num = max_buy_num;
        this.name = name;
        this.price = price;
        this.status = status;
        this.stock = stock;
        this.type_id = type_id;
        this.type_name = type_name;
        this.type_val = type_val;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCurr_stock() {
        return curr_stock;
    }

    public void setCurr_stock(String curr_stock) {
        this.curr_stock = curr_stock;
    }

    public String getDesp() {
        return desp;
    }

    public void setDesp(String desp) {
        this.desp = desp;
    }

    public String getGame_id() {
        return game_id;
    }

    public void setGame_id(String game_id) {
        this.game_id = game_id;
    }

    public String getGame_name() {
        return game_name;
    }

    public void setGame_name(String game_name) {
        this.game_name = game_name;
    }

    public String getGoodId() {
        return goodId;
    }

    public void setGoodId(String goodId) {
        this.goodId = goodId;
    }

    public String getImg() {
        return img;
    }

    public void setImg(String img) {
        this.img = img;
    }

    public String getIs_comm() {
        return is_comm;
    }

    public void setIs_comm(String is_comm) {
        this.is_comm = is_comm;
    }

    public String getMax_buy_num() {
        return max_buy_num;
    }

    public void setMax_buy_num(String max_buy_num) {
        this.max_buy_num = max_buy_num;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPrice() {
        if (price == null) {
            price = "0";
        }
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getStock() {
        return stock;
    }

    public void setStock(String stock) {
        this.stock = stock;
    }

    public String getType_id() {
        return type_id;
    }

    public void setType_id(String type_id) {
        this.type_id = type_id;
    }

    public String getType_name() {
        return type_name;
    }

    public void setType_name(String type_name) {
        this.type_name = type_name;
    }

    public String getType_val() {
        if (type_val == null) {
            type_val = "0";
        }
        return type_val;
    }

    public void setType_val(String type_val) {
        this.type_val = type_val;
    }

}
