package com.gamebox_idtkown.core.db.greendao.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.util.Log;

import org.greenrobot.greendao.AbstractDaoMaster;
import org.greenrobot.greendao.database.StandardDatabase;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseOpenHelper;
import org.greenrobot.greendao.identityscope.IdentityScopeType;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * Master of DAO (schema version 1): knows all DAOs.
 */
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(Database db, boolean ifNotExists) {
        GameInfoDao.createTable(db, ifNotExists);
        GameTypeDao.createTable(db, ifNotExists);
        ChosenInfoDao.createTable(db, ifNotExists);
        GameImageDao.createTable(db, ifNotExists);
        DownloadInfoDao.createTable(db, ifNotExists);
        GameDetailDao.createTable(db, ifNotExists);
        GiftIndexDao.createTable(db, ifNotExists);
        GiftDetailDao.createTable(db, ifNotExists);
        UserInfoDao.createTable(db, ifNotExists);
        PayTypeInfoDao.createTable(db, ifNotExists);
        EarnPointTaskInfoDao.createTable(db, ifNotExists);
        GoodTypeDao.createTable(db, ifNotExists);
        GoodListDao.createTable(db, ifNotExists);
        GoodChangeDao.createTable(db, ifNotExists);
    }

    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(Database db, boolean ifExists) {
        GameInfoDao.dropTable(db, ifExists);
        GameTypeDao.dropTable(db, ifExists);
        ChosenInfoDao.dropTable(db, ifExists);
        GameImageDao.dropTable(db, ifExists);
        DownloadInfoDao.dropTable(db, ifExists);
        GameDetailDao.dropTable(db, ifExists);
        GiftIndexDao.dropTable(db, ifExists);
        GiftDetailDao.dropTable(db, ifExists);
        UserInfoDao.dropTable(db, ifExists);
        PayTypeInfoDao.dropTable(db, ifExists);
        EarnPointTaskInfoDao.dropTable(db, ifExists);
        GoodTypeDao.dropTable(db, ifExists);
        GoodListDao.dropTable(db, ifExists);
        GoodChangeDao.dropTable(db, ifExists);
    }

    /**
     * WARNING: Drops all table on Upgrade! Use only during development.
     * Convenience method using a {@link DevOpenHelper}.
     */
    public static DaoSession newDevSession(Context context, String name) {
        Database db = new DevOpenHelper(context, name).getWritableDb();
        DaoMaster daoMaster = new DaoMaster(db);
        return daoMaster.newSession();
    }

    public DaoMaster(SQLiteDatabase db) {
        this(new StandardDatabase(db));
    }

    public DaoMaster(Database db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(GameInfoDao.class);
        registerDaoClass(GameTypeDao.class);
        registerDaoClass(ChosenInfoDao.class);
        registerDaoClass(GameImageDao.class);
        registerDaoClass(DownloadInfoDao.class);
        registerDaoClass(GameDetailDao.class);
        registerDaoClass(GiftIndexDao.class);
        registerDaoClass(GiftDetailDao.class);
        registerDaoClass(UserInfoDao.class);
        registerDaoClass(PayTypeInfoDao.class);
        registerDaoClass(EarnPointTaskInfoDao.class);
        registerDaoClass(GoodTypeDao.class);
        registerDaoClass(GoodListDao.class);
        registerDaoClass(GoodChangeDao.class);
    }

    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }

    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }

    /**
     * Calls {@link #createAllTables(Database, boolean)} in {@link #onCreate(Database)} -
     */
    public static abstract class OpenHelper extends DatabaseOpenHelper {
        public OpenHelper(Context context, String name) {
            super(context, name, SCHEMA_VERSION);
        }

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(Database db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }

    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name) {
            super(context, name);
        }

        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(Database db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

}
